### ISSUE TITLE
[ASK] Why remove stopwords for embedding?

### ISSUE THREAD

**Issue by igorbrigadir** [microsoft/nlp#395]
### Description

[Embeddings Notebook](https://github.com/microsoft/nlp/blob/master/examples/embeddings/embedding_trainer.ipynb)

Why perform stopword removal before training word embeddings?

Stopword removal is a common preprocessing step, but it is not usually required for building word embeddings. Is there any advantage (apart from slightly reduced vocabulary) to stopword removal for making embeddings? Does it really benefit downstream tasks?

### Other Comments

Removing words before training rather than relying on subsampling hyperparameter has the effect of enlarging the context window for some words.

**Comment by saidbleik** [comment]
You're right, it's an optional step and can be skipped. I think it might still help when your dataset is small or when the task relies on the presence of specific keywords rather than semantics in the text. 
I guess it's best to test the effect of stop words empirically, as it all depends on your dataset (both contents and volume), and the task.
